name: My workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Print Message
      run: echo "Hello, test tags"

    - name: Tagging
      run: |
        echo "v2.0.8-SHA-draft" > manifest.json
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "updated manifest.json"
        git tag v2.0.8-SHA-draft
        git push origin v2.0.8-SHA-draft

